config/routes.rb
Rails.application.routes.draw do
  resources :carros
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/carro.rb
class Carro < ApplicationRecord

	has_many :pais,   class_name: 'CarroCompativelItem', foreign_key: 'carro_pai_id'
  has_many :filhos, class_name: 'CarroCompativelItem', foreign_key: 'carro_filho_id'
  accepts_nested_attributes_for :filhos, allow_destroy: true, reject_if: proc { |attrs| attrs['carro_filho_id'].blank? }

end

app/models/carro_compativel_item.rb
class CarroCompativelItem < ApplicationRecord  
  belongs_to :carro_pai,  class_name: 'Carro'
  belongs_to :filho, 			class_name: 'Carro', foreign_key: :carro_filho_id
  validates :carro_id, :uniqueness => { :scope => :carro_id }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/carros_controller.rb
class CarrosController < ApplicationController
  before_action :set_carro, only: [:show, :edit, :update, :destroy]

  # GET /carros
  # GET /carros.json
  def index
    @carros = Carro.all
  end

  # GET /carros/1
  # GET /carros/1.json
  def show
  end

  # GET /carros/new
  def new
    @carro = Carro.new
  end

  # GET /carros/1/edit
  def edit
  end

  # POST /carros
  # POST /carros.json
  def create
    @carro = Carro.new(carro_params)

    respond_to do |format|
      if @carro.save
        format.html { redirect_to @carro, notice: 'Carro was successfully created.' }
        format.json { render :show, status: :created, location: @carro }
      else
        format.html { render :new }
        format.json { render json: @carro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carros/1
  # PATCH/PUT /carros/1.json
  def update
    respond_to do |format|
      if @carro.update(carro_params)
        format.html { redirect_to @carro, notice: 'Carro was successfully updated.' }
        format.json { render :show, status: :ok, location: @carro }
      else
        format.html { render :edit }
        format.json { render json: @carro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carros/1
  # DELETE /carros/1.json
  def destroy
    @carro.destroy
    respond_to do |format|
      format.html { redirect_to carros_url, notice: 'Carro was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_carro
      @carro = Carro.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def carro_params
      params.require(:carro).permit(:nome, :modelo, :marca)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def link_to_add_fields(name, f, association, link_options={})
		new_object = f.object.send(association).klass.new
		id = new_object.object_id

		fields = f.fields_for(association, new_object, child_index: id) do |builder|
			render("#{new_object.to_partial_path}_fields", f: builder)
		end

		data_options = {id: id, fields: fields.gsub("\n", "")}

		if link_options[:data]
			link_options[:data].merge! data_options
		else
			link_options[:data] = data_options
		end
  
		if link_options[:class]
			link_options[:class] += ' add_fields'
		else
			link_options[:class] = ' add_fields'
		end

		link_to(name, '#', link_options)
	end
end

app/helpers/carros_helper.rb
module CarrosHelper
end

app/views/carro_compativel_itens/_carro_compativel_item_fields.html.erb
<fieldset class="list-group-item" style="background: #fafafa;">
  <%= f.hidden_field :id %>
  <%= f.hidden_field :carro_pai_id, value: @carro.id %>
  <%= f.hidden_field :_destroy, class: 'destroy_field' %>

  <div class="form-group">
    <div class="col-sm-10">
      <%= f.collection_select :carro_filho_id, Carro.all.order(nome: :asc), :id, :nome, { prompt: 'Selecione um carro' }, required: true, class: 'form-control input-large'  %>
    </div>
    <div class="col-sm-2">
  		<%= link_to '#', class: 'remove_fields pull-right' do %>
  		<i class="fa fa-times fa-3x" aria-hidden="true"></i> <% end %>
  	</div>
  </div>

</fieldset>

app/views/carros/_form.html.erb
<%= form_for(carro) do |f| %>
  <% if carro.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(carro.errors.count, "error") %> prohibited this carro from being saved:</h2>

      <ul>
      <% carro.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %>
    <%= f.text_field :nome %>
  </div>

  <div class="field">
    <%= f.label :modelo %>
    <%= f.text_field :modelo %>
  </div>

  <div class="field">
    <%= f.label :marca %>
    <%= f.text_field :marca %>
  </div>

  <div class="panel-body col-sm-10 col-sm-offset-1">
        <div class="list-group">
          <div class="list-group-item"><strong>Perfis Compativeis</strong></div>
          <%= f.fields_for :filhos do |builder| %>
            <%= render "carro_compativel_itens/carro_compativel_item_fields", f: builder %>
          <% end %>
          <div class="list-group-item add-valor">
            <%= link_to_add_fields 'Adicionar', f, :filhos, data: {insert_before: '.add-valor'} %>
          </div>
        </div>
  </div> 

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carros/edit.html.erb
<h1>Editing Carro</h1>

<%= render 'form', carro: @carro %>

<%= link_to 'Show', @carro %> |
<%= link_to 'Back', carros_path %>

app/views/carros/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Carros</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Modelo</th>
      <th>Marca</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carros.each do |carro| %>
      <tr>
        <td><%= carro.nome %></td>
        <td><%= carro.modelo %></td>
        <td><%= carro.marca %></td>
        <td><%= link_to 'Show', carro %></td>
        <td><%= link_to 'Edit', edit_carro_path(carro) %></td>
        <td><%= link_to 'Destroy', carro, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Carro', new_carro_path %>

app/views/carros/new.html.erb
<h1>New Carro</h1>

<%= render 'form', carro: @carro %>

<%= link_to 'Back', carros_path %>

app/views/carros/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @carro.nome %>
</p>

<p>
  <strong>Modelo:</strong>
  <%= @carro.modelo %>
</p>

<p>
  <strong>Marca:</strong>
  <%= @carro.marca %>
</p>

<%= link_to 'Edit', edit_carro_path(@carro) %> |
<%= link_to 'Back', carros_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Teste</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>